name: calvary_attendance
description: "갈보리교회 학생/청년 출결 및 기도제목"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons:

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_auth: ^4.2.0
  firebase_database: ^10.5.7

  # State Management
  provider: ^6.1.2

  # UI & Utilities
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  url_launcher: ^6.1.11
  package_info_plus:

  # UI Components
  panara_dialogs: ^0.1.5
  animated_notch_bottom_bar: ^1.0.3
  elegant_notification: ^2.1.0
  rflutter_alert: ^2.0.7

  # NFC & Deep Link (uni_links to app_links migration)
  nfc_manager: ^4.0.0
  app_links: ^3.5.0

  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
